from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_InsertBooks(object):
    def setupUi(self, InsertBooks):
        InsertBooks.setObjectName("InsertBooks")
        InsertBooks.setWindowIcon(QIcon("images/insp.png"))
        InsertBooks.resize(600, 456)
        InsertBooks.setMinimumSize(QtCore.QSize(600, 456))
        InsertBooks.setMaximumSize(QtCore.QSize(600, 456))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        InsertBooks.setFont(font)
        InsertBooks.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(InsertBooks)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Vladimir Script")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(120, 46, 172);\n"
"background-color: rgb(223, 220, 255);")
        self.label.setPixmap(QtGui.QPixmap("../../images/insp.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.titleGB = QtWidgets.QGroupBox(self.centralwidget)
        self.titleGB.setGeometry(QtCore.QRect(40, 60, 520, 51))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleGB.setFont(font)
        self.titleGB.setStyleSheet("color: rgb(120, 46, 172);")
        self.titleGB.setObjectName("titleGB")
        self.titleTB = QtWidgets.QLineEdit(self.titleGB)
        self.titleTB.setGeometry(QtCore.QRect(5, 20, 510, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.titleTB.setFont(font)
        self.titleTB.setAutoFillBackground(False)
        self.titleTB.setStyleSheet("color: rgb(0, 0, 0);")
        self.titleTB.setFrame(False)
        self.titleTB.setObjectName("titleTB")
        self.authorGB = QtWidgets.QGroupBox(self.centralwidget)
        self.authorGB.setGeometry(QtCore.QRect(40, 120, 520, 51))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.authorGB.setFont(font)
        self.authorGB.setStyleSheet("color: rgb(120, 46, 172);")
        self.authorGB.setObjectName("authorGB")
        self.authorTB = QtWidgets.QLineEdit(self.authorGB)
        self.authorTB.setGeometry(QtCore.QRect(5, 20, 510, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.authorTB.setFont(font)
        self.authorTB.setAutoFillBackground(False)
        self.authorTB.setStyleSheet("color: rgb(0, 0, 0);")
        self.authorTB.setFrame(False)
        self.authorTB.setObjectName("authorTB")
        self.impressionGB = QtWidgets.QGroupBox(self.centralwidget)
        self.impressionGB.setGeometry(QtCore.QRect(40, 180, 520, 101))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.impressionGB.setFont(font)
        self.impressionGB.setStyleSheet("color: rgb(120, 46, 172);")
        self.impressionGB.setObjectName("impressionGB")
        self.impressionTB = QtWidgets.QLineEdit(self.impressionGB)
        self.impressionTB.setGeometry(QtCore.QRect(5, 20, 510, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.impressionTB.setFont(font)
        self.impressionTB.setAutoFillBackground(False)
        self.impressionTB.setStyleSheet("color: rgb(0, 0, 0);")
        self.impressionTB.setFrame(False)
        self.impressionTB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.impressionTB.setObjectName("impressionTB")
        self.likeGB = QtWidgets.QGroupBox(self.centralwidget)
        self.likeGB.setGeometry(QtCore.QRect(40, 290, 520, 51))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.likeGB.setFont(font)
        self.likeGB.setStyleSheet("color: rgb(120, 46, 172);")
        self.likeGB.setObjectName("likeGB")
        self.likeCB = QtWidgets.QComboBox(self.likeGB)
        self.likeCB.setGeometry(QtCore.QRect(5, 20, 510, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.likeCB.setFont(font)
        self.likeCB.setStyleSheet("color: rgb(0, 0, 0);")
        self.likeCB.setMaxVisibleItems(2)
        self.likeCB.setMaxCount(2)
        self.likeCB.setFrame(False)
        self.likeCB.setModelColumn(0)
        self.likeCB.setObjectName("likeCB")
        self.likeCB.addItem('Yes')
        self.likeCB.addItem('No')
        self.likeCB.setCurrentIndex(0)
        self.dateGB = QtWidgets.QGroupBox(self.centralwidget)
        self.dateGB.setGeometry(QtCore.QRect(40, 350, 520, 51))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateGB.setFont(font)
        self.dateGB.setStyleSheet("color: rgb(120, 46, 172);")
        self.dateGB.setObjectName("dateGB")
        self.datePicker = QtWidgets.QDateEdit(self.dateGB)
        self.datePicker.setGeometry(QtCore.QRect(5, 20, 510, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.datePicker.setFont(font)
        self.datePicker.setStyleSheet("color: rgb(0, 0, 0);")
        self.datePicker.setFrame(False)
        self.datePicker.setObjectName("datePicker")
        self.saveB = QtWidgets.QPushButton(self.centralwidget)
        self.saveB.setGeometry(QtCore.QRect(180, 410, 250, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.saveB.setFont(font)
        self.saveB.setStyleSheet("QPushButton{\n"
"color: rgb(120, 46, 172);\n"
"background-color: rgb(223, 220, 255);\n"
"border: none; }\n"
"\n"
"QPushButton:hover{\n"
"font:bold;\n"
"}")
        self.saveB.setAutoDefault(False)
        self.saveB.setDefault(False)
        self.saveB.setFlat(False)
        self.saveB.setObjectName("saveB")
        InsertBooks.setCentralWidget(self.centralwidget)

        self.retranslateUi(InsertBooks)
        QtCore.QMetaObject.connectSlotsByName(InsertBooks)

    def retranslateUi(self, InsertBooks):
        _translate = QtCore.QCoreApplication.translate
        InsertBooks.setWindowTitle(_translate("InsertBooks", "Adding book"))
        self.label.setText(_translate("InsertBooks", "Add a book"))
        self.titleGB.setTitle(_translate("InsertBooks", "Title"))
        self.titleTB.setPlaceholderText(_translate("InsertBooks", "Enter book title..."))
        self.authorGB.setTitle(_translate("InsertBooks", "Author"))
        self.authorTB.setPlaceholderText(_translate("InsertBooks", "Enter book author..."))
        self.impressionGB.setTitle(_translate("InsertBooks", "Impression"))
        self.impressionTB.setPlaceholderText(_translate("InsertBooks", "Enter your impression..."))
        self.likeGB.setTitle(_translate("InsertBooks", "Like"))
        self.dateGB.setTitle(_translate("InsertBooks", "Date of reading"))
        self.saveB.setText(_translate("InsertBooks", "Add"))
